version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - ../.env
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    networks:
      - wildcats-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20
      interval: 10s
      start_period: 40s
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - wildcats-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  wildcats-network:
